// Invoices
export const FETCH_INVOICES = 'FETCH_INVOICES'
export const FETCH_INVOICES_ERROR = 'FETCH_INVOICES_ERROR'

export const CREATE_INVOICE = 'CREATE_INVOICE'
export const CREATE_INVOICE_ERROR = 'CREATE_INVOICE_ERROR'

export const UPDATE_INVOICE = 'UPDATE_INVOICE'
export const UPDATE_INVOICE_ERROR = 'UPDATE_INVOICE_ERROR'

export const DELETE_INVOICE = ' DELETE_INVOICE'
export const DELETE_INVOICE_ERROR =  'DELETE_INVOICE_ERROR'