// Types
export const LOGIN_USER = "LOGIN_USER" 
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR" 

// App addititonal
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
export const FETCH_CATEGORIES_ERROR = 'FETCH_CATEGORIES_ERROR'
export const FETCH_USERS = 'FETCH_USERS'
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR'


// Budgets
export const FETCH_BUDGETS = 'FETCH_BUDGETS'
export const FETCH_BUDGETS_ERROR = 'FETCH_BUDGETS_ERROR'

export const CREATE_BUDGET = 'CREATE_BUDGET'
export const CREATE_BUDGET_ERROR = 'CREATE_BUDGET_ERROR'

export const UPDATE_BUDGET = 'UPDATE_BUDGET'
export const UPDATE_BUDGET_ERROR = 'UPDATE_BUDGET_ERROR'

export const DELETE_BUDGET = 'DELETE_BUDGET'
export const DELETE_BUDGET_ERROR =  'DELETE_BUDGET_ERROR'

// Revenues
export const FETCH_REVENUES = 'FETCH_REVENUES'
export const FETCH_REVENUES_ERROR = 'FETCH_REVENUES_ERROR'

export const CREATE_REVENUE = 'CREATE_REVENUE'
export const CREATE_REVENUE_ERROR = 'CREATE_REVENUE_ERROR'

export const UPDATE_REVENUE = 'UPDATE_REVENUE'
export const UPDATE_REVENUE_ERROR = 'UPDATE_REVENUE_ERROR'

export const DELETE_REVENUE = 'DELETE_REVENUE'
export const DELETE_REVENUE_ERROR =  'DELETE_REVENUE_ERROR'

// Scans
export const FETCH_SCANS = 'FETCH_SCANS'
export const FETCH_SCANS_ERROR = 'FETCH_SCANS_ERROR'

export const CREATE_SCAN = 'CREATE_SCAN'
export const CREATE_SCAN_ERROR = 'CREATE_SCAN_ERROR'

export const UPDATE_SCAN = 'UPDATE_SCAN'
export const UPDATE_SCAN_ERROR = 'UPDATE_SCAN_ERROR'

export const DELETE_SCAN = 'DELETE_SCAN'
export const DELETE_SCAN_ERROR =  'DELETE_SCAN_ERROR'

// Invoices
export const FETCH_INVOICES = 'FETCH_INVOICES'
export const FETCH_INVOICES_ERROR = 'FETCH_INVOICES_ERROR'

export const CREATE_INVOICE = 'CREATE_INVOICE'
export const CREATE_INVOICE_ERROR = 'CREATE_INVOICE_ERROR'

export const UPDATE_INVOICE = 'UPDATE_INVOICE'
export const UPDATE_INVOICE_ERROR = 'UPDATE_INVOICE_ERROR'

export const DELETE_INVOICE = ' DELETE_INVOICE'
export const DELETE_INVOICE_ERROR =  'DELETE_INVOICE_ERROR'

// Importers
export const FETCH_IMPORTERS = 'FETCH_IMPORTERS'
export const FETCH_IMPORTERS_ERROR = 'FETCH_IMPORTERS_ERROR'

export const CREATE_IMPORTER = 'CREATE_IMPORTER'
export const CREATE_IMPORTER_ERROR = 'CREATE_IMPORTER_ERROR'

export const UPDATE_IMPORTER = 'UPDATE_IMPORTER'
export const UPDATE_IMPORTER_ERROR = 'UPDATE_IMPORTER_ERROR'

export const DELETE_IMPORTER = ' DELETE_IMPORTER'
export const DELETE_IMPORTER_ERROR =  'DELETE_IMPORTER_ERROR'

// Coworkers
export const FETCH_COWORKERS = 'FETCH_COWORKERS'
export const FETCH_COWORKERS_ERROR = 'FETCH_COWORKERS_ERROR'

export const CREATE_COWORKER = 'CREATE_COWORKER'
export const CREATE_COWORKER_ERROR = 'CREATE_COWORKER_ERROR'

export const UPDATE_COWORKER = 'UPDATE_COWORKER'
export const UPDATE_COWORKER_ERROR = 'UPDATE_COWORKER_ERROR'

export const DELETE_COWORKER = ' DELETE_COWORKER'
export const DELETE_COWORKER_ERROR =  'DELETE_COWORKER_ERROR'

// Accounts
export const FETCH_ACCOUNTS = 'FETCH_ACCOUNTS'
export const FETCH_ACCOUNTS_ERROR = 'FETCH_ACCOUNTS_ERROR'

export const CREATE_ACCOUNT = 'CREATE_ACCOUNT'
export const CREATE_ACCOUNT_ERROR = 'CREATE_ACCOUNT_ERROR'

export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT'
export const UPDATE_ACCOUNT_ERROR = 'UPDATE_ACCOUNT_ERROR'

export const DELETE_ACCOUNT = ' DELETE_ACCOUNT'
export const DELETE_ACCOUNT_ERROR =  'DELETE_ACCOUNT_ERROR'

// Facilities
export const FETCH_FACILITIES = 'FETCH_FACILITIES'
export const FETCH_FACILITIES_ERROR = 'FETCH_FACILITIES_ERROR'

export const CREATE_FACILITY = 'CREATE_FACILITY'
export const CREATE_FACILITY_ERROR = 'CREATE_FACILITY_ERROR'

export const UPDATE_FACILITY = 'UPDATE_FACILITY'
export const UPDATE_FACILITY_ERROR = 'UPDATE_FACILITY_ERROR'

export const DELETE_FACILITY = ' DELETE_FACILITY'
export const DELETE_FACILITY_ERROR =  'DELETE_FACILITY_ERROR'

// Signals
export const FETCH_SIGNALS = 'FETCH_SIGNALS'
export const FETCH_SIGNALS_ERROR = 'FETCH_SIGNALS_ERROR'

export const DELETE_SIGNAL = ' DELETE_SIGNAL'
export const DELETE_SIGNAL_ERROR =  'DELETE_SIGNAL_ERROR'

export const DELETE_ALL_SIGNALS = ' DELETE_ALL_SIGNALS'
export const DELETE_ALL_SIGNALS_ERROR =  'DELETE_ALL_SIGNALS_ERROR'

